name: 'update the csv custom parameters'
description: 'update the operator image and minimume kubernetes version values in the csv yaml file'
inputs:
  current_operator_image:
    description: 'The folder to copy the files to'
    required: true
  wanted_operator_image:
    description: 'The folder to copy the files to'
    required: true
  csv_file:
    description: 'The folder to copy the files to'
    required: true
runs:
  using: "composite"
  steps: 
    - name: prepare_env
      id: environment_setup
      run: |
        sed -i "s+${{ inputs.current_operator_image }}+${{ inputs.wanted_operator_image }}+g" ${{ inputs.csv_file }}