name: 'update the csv custom parameters'
description: 'update the operator image and minimume kubernetes version values in the csv yaml file'
inputs:
  current_operator_image:
    description: 'The current operator image in the csv yaml file'
    required: true
  wanted_operator_image:
    description: 'The wanted operator image to be in the csv yaml file'
    required: true
  csv_file:
    description: 'The csv yaml file path'
    required: true
  repository_path:
    description: 'The path that all the repo files are'
    required: true
runs:
  using: "composite"
  steps: 
    - name: update_csv
      id: environment_setup
      run: |
        build/ci/update_csv.sh
      shell: bash
      env:
        current_image: ${{ inputs.current_operator_image }}
        wanted_image: ${{ inputs.wanted_operator_image }}
        csv_file: ${{ inputs.csv_file }}
        repository_path: ${{ inputs.repository_path }}
