name: Operator test

env:
  OP_TEST_DEBUG: 1
  OP_TEST_CONTAINER_OPT: "-t"
on:
  push:
    branches:
    - main
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
   outputs:
     operator_image: "csiblock1/ibm-block-csi-operator-amd64:new"

  CI-csi-kiwi:
    name: "matan test CI"
    needs: operator_image_build
    runs-on: ubuntu-latest
    steps:
      - id: prepare_env
        uses: matancarmeli7/test_pipeline@v1 
      - name: kiwi / Full operator test
        run: |
          echo "kiwi ${{ steps.prepare_env.outputs.community_operators_path }}"
          scripts/ci/op-test kiwi "${{ steps.prepare_env.outputs.community_operators_path }}"
      - name: check cluster
        run: |
          kubectl get pods -A
