name: Operator test

env:
  OP_TEST_DEBUG: 1
  OP_TEST_CONTAINER_OPT: "-t"
on:
  push:
    branches:
    - main
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
   outputs:
     operator_image: "csiblock1/ibm-block-csi-operator-amd64:new"

  prepare_env:
   name: "prepare_env"
   needs: operator_image
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip yq
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: prepare_env
        id: environment_setup
        env:
          operator_image: ${{ needs.operator_image_build.outputs.operator_image }}
        run: |
          build/ci/prepare_env.sh
   outputs:
     current_operator_image: "${{ steps.environment_setup.outputs.current_operator_image }}"
     wanted_operator_image: "${{ steps.environment_setup.outputs.wanted_operator_image }}"
     csv_file: "${{ steps.environment_setup.outputs.csv_file }}"
     community_operators_path: "${{ steps.environment_setup.outputs.community_operators_path }}"

  CI-csi-kiwi:
    name: "matan test CI"
    needs: prepare_env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: update_csv
        uses: matancarmeli7/test_pipeline@v1 
        with:
          current_operator_image: ${{ needs.prepare_env.outputs.current_operator_image }}
          wanted_operator_image: ${{ needs.prepare_env.outputs.wanted_operator_image }}
          csv_file: ${{ needs.prepare_env.outputs.csv_file }}
      - name: kiwi / Full operator test
        run: |
          echo "kiwi ${{ needs.prepare_env.outputs.community_operators_path }}"
          build/ci/op-test kiwi "${{ needs.prepare_env.outputs.community_operators_path }}"
      - name: check cluster
        run: |
          kubectl get pods -A
