name: Operator test

on:
  push:
    branches:
    - main
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: install gh
        run: |
          git config --global user.email csi.block1@il.ibm.com
          git config --global user.name csiblock
          echo $'yq() {\n  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"\n}' >> /home/runner/.bashrc
      - name: Save gitconfig file
        uses: actions/upload-artifact@v2
        with:
          name: gitconfig-file
          path: |
            /home/runner/.gitconfig
            /home/runner/.bashrc

  use_gh:
   name: "use gh"
   needs: operator_image_build
   runs-on: ubuntu-latest
   steps:
      - name: Retrieve gitconfig file
        uses: actions/download-artifact@v2
        with:
          name: gitconfig-file
          path: /home/runner
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: move downloaded files to original paths
        run: |
          mv /home/runner/home/runner/.gitconfig /home/runner/.gitconfig
          mv /home/runner/home/runner/.bashrc /home/runner/.bashrc
      - name: check yq
        run: |
          yq
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
