on:
  push:
    branches:
    - main
jobs:
  test-csi:
    name: "matan test CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: clone operator-test-playbooks repo
        uses: actions/checkout@master
        with:
          repository: operator-framework/operator-test-playbooks
      - name: Operator test
        run: |
          ls -l
