name: Operator test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Setup tmate session
        run: echo ${{ github.ref }}
      - name: install gh
        run: |
          git config --global user.email csi.block1@il.ibm.com
          git config --global user.name csiblock
          echo $'yq() {\n  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"\n}' >> /home/runner/.bash_profile
      - name: Save gitconfig file
        uses: actions/upload-artifact@v2
        with:
          name: gitconfig-file
          path: |
            /home/runner/.gitconfig
            /home/runner/.bash_profile

  use_gh:
   name: "use gh"
   needs: operator_image_build
   runs-on: ubuntu-latest
   steps:
      - name: Retrieve gitconfig file
        uses: actions/download-artifact@v2
        with:
          name: gitconfig-file
          path: /home/runner
      - name: check yq
        shell: bash -l {0}
        run: |
          yq
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
