on:
  push:
    branches:
    - main
jobs:
  test-csi:
    name: "matan test CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: orgname/reponame
      - name: Operator test
        run: |
          ls -l
