name: Operator test

on:
  push:
    branches:
    - main
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: install gh
        run: |
          git config --global user.email csi.block1@il.ibm.com
          git config --global user.name csiblock
          echo $'yq() {\n  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"\n}' >> /home/runner/.bashrc
#          echo $'yq() {\n  docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"\n}' >> /home/runner/.bash_profile
      - name: Save gitconfig file
        uses: actions/upload-artifact@v2
        with:
          name: gitconfig-file
          path: |
            /home/runner/.gitconfig
            /home/runner/.bashrc
            /home/runner/.bash_profile

  use_gh:
   name: "use gh"
   needs: operator_image_build
   runs-on: ubuntu-latest
   steps:
      - name: Retrieve gitconfig file
        uses: actions/download-artifact@v2
        with:
          name: gitconfig-file
          path: /home/runner
      - name: check yq
        run: |
          source /home/runner/.bashrc
          yq
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
