name: Operator test

on:
  push:
    branches:
    - main
jobs:
  operator_image_build:
   name: "set env"
   runs-on: ubuntu-latest
   steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install gh
        run: |
          git config --global user.email csi.block1@il.ibm.com
          git config --global user.name csiblock
          sudo snap install yq
      - name: Save gitconfig file
        uses: actions/upload-artifact@v2
        with:
          name: gitconfig-file
          path: |
            /home/runner/.gitconfig
            /snap/bin/yq

  use_gh:
   name: "use gh"
   needs: operator_image_build
   runs-on: ubuntu-latest
   steps:
      - name: Retrieve gitconfig file
        uses: actions/download-artifact@v2
        with:
          name: gitconfig-file
          path: /home/runner
      - name: move downloaded files to original paths
        run: |
          mv /home/runner/home/runner/.gitconfig /home/runner/.gitconfig
          sudo mv /home/runner/snap/bin/yq /snap/bin/yq
          sudo chmod 777 /snap/bin/yq
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
